### ISSUE TITLE
Severity Flapping

### ISSUE THREAD

**Issue by zachmoody** [guardian/alerta#344]
Hello! I'm trying to run down an odd transient issue we sometimes see when a prometheus alert goes from warning/major to critical and back to warning/major. It will sometimes get stuck in a loop of sorts where instead of de-duplicating the event it is instead closed with `correlated alert status change` (because, I'm guessing, the alert with `severity = critical` was closed), and a new event is created. 

Which repeats every time alertmanager sends another event.

I'm attaching a [log](https://github.com/guardian/alerta/files/817777/alerta-flap.txt) of one of these events, but I have some more if you want them. Just wanted to float the issue and see if you've seen something similar or might have an idea of what it might be.

We're running `v4.8.3`

Thanks!

**Comment by satterly** [comment]
Hi @zachmoody Thanks for the heads up. I'll take a look when I get a chance.

In the meantime, have you seen this tutorial which steps you through creating a plugin that will detect flapping alerts and do whatever you want with them ? http://alerta.readthedocs.io/en/latest/gettingstarted/tutorial-3-plugins.html?highlight=flapping#step-2-write-a-plugin

**Comment by satterly** [comment]
I suspect this has to do with a warning and a major rule both firing for the same resource.
For example, if the rules are like this...
```
ALERT warning IF RxUtil >= 80%
ALERT major IF RxUtil >= 90%
```
... then when RxUtil = 91% both the warning and major rule will match.
I would guess you need to adjust the warning rule to something like ...
```
ALERT warning IF RxUtil >= 80% AND RxUtil < 90%
ALERT major IF RxUtil >= 90%
```
Without seeing your alertmanager rules I can't be sure though.

**Comment by zachmoody** [comment]
@satterly We have inhibit rules that keep warning's suppressed when a major is firing on the same instance. Same goes for major to critical. It's been a while since this has happened, but I seem to remember verifying in alertmanager we're suppressing the more minor alert when this is happening.

Here's the alert manager config though:

```
route:
  receiver: alerta
  repeat_interval: 60s
  group_wait: 10s
  group_interval: 10s

inhibit_rules:
- source_match:
    severity: 'major'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']

- source_match:
    severity: 'critical'
  target_match:
    severity: 'major'
  equal: ['alertname', 'instance']

- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']

receivers:
- name: alerta
  webhook_configs:
  - url: '{{alerta_url}}'
    send_resolved: true
```
